# docker-compose.yml
# start with   docker-compose up -d
# version: '3.9'

services:

  portal:       # based on nginx build. Has the config file in it.
    image: davidhay25/canshare-portal
    container_name: canshare-portal
    ports:
      - "80:80"
    networks:
      - canshare-network
    depends_on:
      - forms
      - canshare

  forms:
    image: davidhay25/forms:v1.0.0
    container_name: forms
    depends_on:
      - mongodb                      # ensures MongoDB starts first
    environment:
      MONGOHOSTNAME: mongodb
      ENVIRONMENT: canshare    # some options are hidden in canshare
      MONGODB: clinfhir        # name of the mongo database. Only accessed by this container as the monodb is internal
    ports:
      - "9500:9500"                  # hostPort:containerPort for web access
    networks:
      - canshare-network

  # mongo port is not exposed outside of the docker network...
  mongodb:
    image: mongo:4.4
    platform: linux/amd64     # ðŸ‘ˆ force Intel-compatible build <<< only on mac - need to fix b4 deploy
    restart: always
    networks:
      - canshare-network
    volumes:
      - ./mongodb_data:/data/db       # bind to a path - won't get deleted with docker compose down -v

  canshare:
    image: davidhay25/canshare
    container_name: canshare
    depends_on:
      - mongodb                      # ensures MongoDB starts first
    environment:
      MONGOHOSTNAME: mongodb
      MONGODB: canshare-lim           # use a separate database for the canshare app. models.html will then use a separate db to cfForms
      POCSERVERBASE: "9400"           # set the canshare server to start on port 9400 (must match dockerfile)
    ports:
      - "9400:9400"                  # hostPort:containerPort for web access
    networks:
      - canshare-network

  oldforms:
    image: davidhay25/oldforms
    container_name: oldforms
    depends_on:
      - mongodb                      # ensures MongoDB starts first

    ports:
      - "9090:9090"                  # hostPort:containerPort for web access
    networks:
      - canshare-network

networks:
  canshare-network:
    driver: bridge
